<a href="https://colab.research.google.com/github/asaitej1/data690_Sai-Teja/blob/main/Individual_project_part-B/Individual__project_part_B.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
import plotly

print(plotly.__version__)

5.3.1

In [3]:
!pip install plotly  --upgrade

Requirement already satisfied: plotly in /usr/local/lib/python3.7/dist-packages (5.3.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.7/dist-packages (from plotly) (8.0.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from plotly) (1.15.0)

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/DATA-690-FALL-2021/data690_Sai-Teja/main/Individual_project_part-B/wdi_data%20(5).csv")
df

     Unnamed: 0  Year  ...         Income Group    Lending Type
0             0  2015  ...  Lower middle income             IDA
1             1  2016  ...  Lower middle income             IDA
2             2  2017  ...  Lower middle income             IDA
3             3  2018  ...  Lower middle income             IDA
4             4  2019  ...  Lower middle income             IDA
..          ...   ...  ...                  ...             ...
192         192  2015  ...          High income  Not classified
193         193  2016  ...          High income  Not classified
194         194  2017  ...          High income  Not classified
195         195  2018  ...          High income  Not classified
196         196  2019  ...          High income  Not classified

[197 rows x 9 columns]

In [5]:
df.drop(columns=["Unnamed: 0"],inplace=True)
df

     Year      value  ...         Income Group    Lending Type
0    2015  26.831395  ...  Lower middle income             IDA
1    2016  27.346118  ...  Lower middle income             IDA
2    2017  27.750900  ...  Lower middle income             IDA
3    2018  28.536988  ...  Lower middle income             IDA
4    2019  29.648679  ...  Lower middle income             IDA
..    ...        ...  ...                  ...             ...
192  2015  78.690244  ...          High income  Not classified
193  2016  78.539024  ...          High income  Not classified
194  2017  78.539024  ...          High income  Not classified
195  2018  78.639024  ...          High income  Not classified
196  2019  78.787805  ...          High income  Not classified

[197 rows x 8 columns]

In [6]:
df_2015 = df.query("Year == 2015")
df_2015.sample(10)

     Year         value  ...         Income Group    Lending Type
138  2015  1.440000e+01  ...          High income  Not classified
6    2015  4.084134e+01  ...  Upper middle income            IBRD
18   2015  1.841990e+01  ...          High income  Not classified
123  2015  8.100000e+00  ...  Upper middle income            IBRD
29   2015  3.555505e+03  ...  Lower middle income             IDA
35   2015  1.297877e+04  ...  Upper middle income            IBRD
155  2015  4.192291e+01  ...  Lower middle income            IBRD
12   2015  2.734739e+01  ...  Lower middle income            IBRD
59   2015  1.733667e+01  ...  Lower middle income             IDA
100  2015  1.310152e+09  ...  Lower middle income            IBRD

[10 rows x 8 columns]

In [7]:
df_2015 = df_2015.query("indicator in['NE.EXP.GNFS.ZS','NE.TRD.GNFS.ZS','NV.IND.TOTL.ZS','NY.GDP.PCAP.PP.CD']")
df_2015.head()

    Year      value  ...         Income Group    Lending Type
0   2015  26.831395  ...  Lower middle income             IDA
6   2015  40.841340  ...  Upper middle income            IBRD
12  2015  27.347391  ...  Lower middle income            IBRD
18  2015  18.419902  ...          High income  Not classified
24  2015  18.544508  ...          High income  Not classified

[5 rows x 8 columns]

In [8]:
df_pivot = df_2015.pivot(index =['Country Code','Country Name','Region','Income Group','Lending Type'], columns='indicator', values='value').reset_index()
df_pivot.head()

indicator Country Code    Country Name  ... NV.IND.TOTL.ZS NY.GDP.PCAP.PP.CD
0                  BGD      Bangladesh  ...      26.831395       3555.505260
1                  CHN           China  ...      40.841340      12978.768911
2                  GBR  United Kingdom  ...      18.419902      42567.591797
3                  IND           India  ...      27.347391       5464.859178
4                  USA   United States  ...      18.544508      56863.371496

[5 rows x 9 columns]

In [9]:
df_pivot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Country Code       5 non-null      object
 1   Country Name       5 non-null      object
 2   Region             5 non-null      object
 3   Income Group       5 non-null      object
 4   Lending Type       5 non-null      object
 5   NE.EXP.GNFS.ZS     5 non-null      float64
 6   NE.TRD.GNFS.ZS     5 non-null      float64
 7   NV.IND.TOTL.ZS     5 non-null      float64
 8   NY.GDP.PCAP.PP.CD  5 non-null      float64
dtypes: float64(4), object(5)
memory usage: 488.0+ bytes

In [10]:
fig = px.bar(
    df_pivot,
    x="Country Name",
    y="NE.EXP.GNFS.ZS",
    title="TOP 5 Countries by 2015 Exports of goods and services (% of GDP)",
    color='Country Name',
    labels={"NE.EXP.GNFS.ZS":"2015 Exports of goods and services (% of GDP)"}
).update_xaxes(categoryorder="total descending")
fig.show()

In [11]:
df2 = df.query("indicator in['NE.EXP.GNFS.ZS','NE.TRD.GNFS.ZS','NV.IND.TOTL.ZS','NY.GDP.PCAP.PP.CD']")
df2.head()

   Year      value  ...         Income Group Lending Type
0  2015  26.831395  ...  Lower middle income          IDA
1  2016  27.346118  ...  Lower middle income          IDA
2  2017  27.750900  ...  Lower middle income          IDA
3  2018  28.536988  ...  Lower middle income          IDA
4  2019  29.648679  ...  Lower middle income          IDA

[5 rows x 8 columns]

In [12]:
df_pivot2 = df2.pivot(index =['Year','Country Code','Country Name','Region','Income Group','Lending Type'], columns='indicator', values='value').reset_index()
df_pivot2.head()

indicator  Year Country Code  ... NV.IND.TOTL.ZS NY.GDP.PCAP.PP.CD
0          2015          BGD  ...      26.831395       3555.505260
1          2015          CHN  ...      40.841340      12978.768911
2          2015          GBR  ...      18.419902      42567.591797
3          2015          IND  ...      27.347391       5464.859178
4          2015          USA  ...      18.544508      56863.371496

[5 rows x 10 columns]

In [13]:
fig = px.line(df_pivot2,
    x="Year",
    y="NV.IND.TOTL.ZS",
    title="TOP 5 Countries by 2015 Industry (including construction), value added (% of GDP)",
    color='Country Name',
    labels={"Year":"Year","NV.IND.TOTL.ZS":"Industry (including construction), value added<br>(% of GDP)"},
    hover_name='Country Name',
    
)
fig.show()

In [14]:
fig = px.bar(
    df_pivot,
    x="Country Name",
    y="NE.TRD.GNFS.ZS",
    title="TOP 5 Countries by 2015 Trade (% of GDP)",
    color='Country Name',
    labels={"NE.TRD.GNFS.ZS":"2015 Trade (% of GDP)"}
).update_xaxes(categoryorder="total descending")
fig.show()

In [15]:
fig = px.pie(
    df_pivot,
    values='NY.GDP.PCAP.PP.CD', 
    names='Country Name',
    title='TOP 5 Countries by 2015 GDP per capita, PPP (current international $)',
    hover_name='Country Code',
)
fig.update_traces(textposition='inside', textinfo='percent+label')
fig.show()